### PR TITLE
Added link to blog post with with overview of honeypots supported

### PR DESCRIPTION
**Pull request by eludom**

### CODE REVIEW

**Comment by jt6211** [comment]
@eludom would you be opposed to me adding this content to our wiki?  I would prefer to keep the MHN project self contained in terms of documentation like this.

**Comment by eludom** [comment]
That's fine.   It just looked like a little too much for the README as I wrote it.

**Comment by eludom** [comment]
Other thing you could do in the REAME is have the quick references to the various honeypots actually link to their home sites.   Would not clutter the README, and, as long as the the sites to your upstream honeypots stay valid, you only depend on them (which you already do)

**Comment by jt6211** [comment]
That seems like a good idea.  Thanks George.
​

**Pull request merged**
