### PR TITLE
UI enhancement and fix for issue #473

### PR DESCRIPTION
**Pull request by joeneldeasis**

### CODE REVIEW

**Comment by d1str0** [comment]
I like this, however I'd like to see the footer remain: "Modern Honeynet Framework is an open source project by: [logo]"

**Comment by d1str0** [comment]
Also, I'd definitely merge a change for  "LOGIN" to be "Log In" and "LOGOUT" to be "Log Out", but I can live without that or change that myself.

**Comment by joeneldeasis** [comment]
Done editing the template, please check the latest commit.

**Comment by joeneldeasis** [comment]
Fixed API Information Leak #473

**Comment by d1str0** [comment]
Unfortunately this does not fully fix #473, although it does help in a way. Thanks for the PR!

**Pull request merged**
