### PR TITLE
Debian7 install

### PR DESCRIPTION
**Pull request by sidra-asa**
I've done some works on installing scripts, making them works on Debian 7. It seems OK on mhn server installation, and I'll keep doing test and improvement. I'll be grateful if any advise or feedback.

### CODE REVIEW

**Comment by deanboole** [comment]
this is great! :100:

**Comment by gregcmartin** [comment]
awesome work!

**Comment by jt6211** [comment]
@sidra-asa thanks for doing all this work.  This is awesome.  I am collecting some feedback.

**Comment by Keldo** [comment]
Trouble on 64bit Debian 7...  mongo-org-server fails to install.

**Comment by sidra-asa** [comment]
@Keldo  Could you provide specific information ?

**Comment by sanderu** [comment]
MongoDB server install script fixed in pull request https://github.com/threatstream/mhn/pull/299

**Comment by d1str0** [comment]
We're now on Debian 9, we may support pure debian installs in the future but 7 is quite old.

**Pull request closed without merging**
