### PR TITLE
review ok

### PR DESCRIPTION
**Pull request by scopion**
review ok

### CODE REVIEW

**Comment by d1str0** [comment]
@scopion in the future, please provide a description of what the PR is for. This is a very vague title.

**Comment by d1str0** [comment]
Unfortunately, this PR seems very specific to your personal operating needs. Much of these changes are not beneficial to the community of MHN. However, your alterations on a couple of these deploy scripts may prove beneficial. In the meantime, I will be closing this PR.

**Comment by scopion** [comment]
@d1str0 you are right.The alarm.py file is my personal operating needs. And  some deploy scripts are out of date,so i updated some of them. I have changed the mongo ,docker ,snort ,dionaea install script . The Shodan can recognize the dionaea honey pot ,so i changed some thing in the docker file and pushed to the cloud. these are all the changes.

**Comment by d1str0** [comment]
Thank you. We may incorporate some of the RHEL changes you submitted as we update the installers and deploy scripts.

**Pull request closed without merging**
