### PR TITLE
Update deploy_snort.sh

### PR DESCRIPTION
**Pull request by DuckY1987**
Static Interface selection replaced with auto-select eth0/ens160

### CODE REVIEW

**Comment by d1str0** [comment]
Does this work for you? When it greps for the IP, I find that on Ubuntu 18 it fails. I have changed it to,
```
IP=$(ifconfig $INTERFACE | grep 'inet' | cut -f2 -d: | awk '{print $1}')
```

**Comment by DuckY1987** [comment]
Thought the sensors mostly are not supported on ubuntu 18.04 yet, im working on the ubuntu 18.04 support. I will verify centos too and get back to you with an update, there was a breaking change from 16.04 to 18.04, before it was inet addr, now its just inet....need to figure out how to change it on demand according to the release version.

**Comment by DuckY1987** [comment]
this part i didn't even change i just noticed ;-)

**Comment by d1str0** [comment]
Some of the scripts already check on 16.04 vs 18.04, so that's easy, but I'm curious if there's a single command that might work between both.

And yeah, I've only just noticed this breaks in 18.04 and it's not related to your change at all, but it would be useful to add. 

The goal is to support 16 and 18 for all scripts, and Raspberry Pi when possible.

**Comment by d1str0** [comment]
For example: https://github.com/threatstream/mhn/blob/master/scripts/install_mongo.sh

**Comment by DuckY1987** [comment]
@d1str0 perfect, i was working on smth similar today. Too many solutions to decide :-D.

**Comment by DuckY1987** [comment]
@d1str0 lsb_release is not available on centos for instance.... thats why i tried to find another solution.

**Comment by d1str0** [comment]
I'm not too sure how many people are using centos tbh.

**Comment by DuckY1987** [comment]
@d1str0 well i commited already my simply solution, assuming one interface is configured.

hostname -I works great. Verified on 16.04, 18.04, Centos 6.1 and 7.5

**Comment by d1str0** [comment]
Testing myself right now, then I'll merge :)

**Comment by DuckY1987** [comment]
@d1str0 too many solutions, found a better one :-) as well verified on all distris.

Ip=$(ip -f inet -o addr show $INTERFACE|cut -d\  -f 7 | cut -d/ -f 1)

**Comment by DuckY1987** [comment]
Works on Ubuntu 18.04 and 16.04 just verified.

**Comment by d1str0** [comment]
Fails on Digital Ocean as it can have a public and private IP causing `P=$(ip -f inet -o addr show $INTERFACE|cut -d\ -f 7 | cut -d/ -f 1)` to produce two lines of IPs breaking the config.

To get the first line (public IP on digital ocean install), I added `head -n 1`

**Pull request merged**
