### PR TITLE
Change Support to CentOS 7

### PR DESCRIPTION
**Pull request by Philelis**
Installation for CentOS 7 instead 6.

### CODE REVIEW

**Comment by Philelis** [comment]
No one interested to use a newer os verion?

**Comment by Philelis** [comment]
@dpicollege  You can see my changes at: [Philelis/mhn](https://github.com/Philelis/mhn/commits/master)
Only click on the last commits from me and change the files you need :) 
If you want to install it please also do that fix: #386

**Comment by dpicollege** [comment]
thanks @Philelis i always have this error #394 no rule update after 12h.
are your suricata and snort rule update every 12h?

**Comment by Philelis** [comment]
I think your problem is `$HOME_NET any ` change this to your server Ip or the net that you want to monitor.

**Comment by dpicollege** [comment]
this is not the case you are talking about. i mean in mhn server rule dosen't update every 12h. check it out your server does celery work like charm and the rule insert in your sqllite db?

**Comment by Philelis** [comment]
No I don't see your error.
I have 20704 rules.

**Comment by d1str0** [comment]
This isn't working properly for me at this time. I cannot seem to get Centos 7 working at all ATM.

**Comment by d1str0** [comment]
@Philelis testing this on a centos 7 Digital Ocean droplet fails.

**Comment by Philelis** [comment]
@d1str0 Hey I am out of the newest changes, but I will see what I can do. Can you send me your errors?

**Comment by d1str0** [comment]
I'm getting permission errors from nginx trying talk to uwsgi. Also, by default, the nginx conf doesn't work and it instead points to the default "nginx is running" web pages instead of MHN. I tried quite a bit to resolve the permissions error.

**Comment by d1str0** [comment]
@Philelis I've since killed the droplet for Centos7, but if you're using an up to date system you should see the same issues on a fresh install. Lmk if there's anything I can do to help collab on this. I'm putting centos7 support on the backburner for the moment as I've spent quite a while on this.

**Comment by Philelis** [comment]
Thanks @d1str0, I will have a look on it and hopefully fix it :)

**Comment by d1str0** [comment]
@Philelis lmk if you make any progress. MOving forward we will only officially be supporting the currently supported Ubuntu systems until we can get someone to figure out the Centos issues. :)

**Pull request closed without merging**
