### PR TITLE
Ubuntu 16 support

### PR DESCRIPTION
**Pull request by jt6211**

### CODE REVIEW

**Comment by jt6211** [comment]
Deployed MHN, deployed a honeypot, honeymap working (events showing up), data showing up in mongo, attacks page, etc.

```
root@mhn:/opt/mnemosyne# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
root@mhn:/opt/mnemosyne# supervisorctl status
geoloc                           RUNNING   pid 31957, uptime 0:38:51
honeymap                         RUNNING   pid 31958, uptime 0:38:51
hpfeeds-broker                   RUNNING   pid 12469, uptime 0:41:32
mhn-celery-beat                  RUNNING   pid 1481, uptime 0:29:02
mhn-celery-worker                RUNNING   pid 1573, uptime 0:22:59
mhn-collector                    RUNNING   pid 1483, uptime 0:29:02
mhn-uwsgi                        RUNNING   pid 1487, uptime 0:29:02
mnemosyne                        RUNNING   pid 18596, uptime 0:05:51
root@mhn:/opt/mnemosyne# 
root@mhn:/opt/mnemosyne# 
root@mhn:/opt/mnemosyne# netstat -luntp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:27017         0.0.0.0:*               LISTEN      10226/mongod    
tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN      481/redis-server 12
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      1520/nginx -g daemo
tcp        0      0 0.0.0.0:10000           0.0.0.0:*               LISTEN      12469/python    
tcp        0      0 0.0.0.0:8181            0.0.0.0:*               LISTEN      18596/python    
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1626/sshd       
tcp6       0      0 :::22                   :::*                    LISTEN      1626/sshd       
tcp6       0      0 :::3000                 :::*                    LISTEN      31958/server    
```

**Comment by mwollenweber** [comment]
lgtm. Will run a quick test on a ubuntu 16 vm, assuming no problems will merge.

**Comment by cloughrm** [comment]
Thanks for adding this @jt6211 !

**Comment by jt6211** [comment]
No prob :)

**Pull request merged**
