### PR TITLE
Upgrade py-bcrypt to bcrypt

### PR DESCRIPTION
**Pull request by iankronquist**
Fixes issue #244 on GitHub.

### CODE REVIEW

**Comment by iankronquist** [comment]
Anyone interested in taking a look at this?

**Comment by jt6211** [comment]
Ian, did you test this and it worked?

**Comment by iankronquist** [comment]
IbthinknI didnsome minimal testing but didn't find instructions for running any unit tests

**Comment by jt6211** [comment]
@iankronquist I am testing this now on both ubuntu and centos.  i just want to make sure it doesn't break anything unexpectedly.

**Comment by iankronquist** [comment]
@jt6211 Are you still interested in this PR? Is there any additional testing you would like me to do?

**Comment by iankronquist** [comment]
@jt6211 thanks!

**Pull request merged**
